name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Update frontend dependencies
        working-directory: expense-tracker
        run: |
          npm update
          npm audit fix --audit-level moderate

      - name: Update backend dependencies
        working-directory: functions
        run: |
          npm update
          npm audit fix --audit-level moderate

      - name: Run tests after updates
        working-directory: expense-tracker
        run: npm test -- --watchAll=false --passWithNoTests

      - name: Run backend tests after updates
        working-directory: functions
        run: npm test --passWithNoTests 2>/dev/null || echo "No backend tests"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            🔄 chore: update dependencies

            - Updated frontend dependencies
            - Updated backend dependencies
            - Fixed security vulnerabilities
            - All tests passing
          title: '🔄 Weekly Dependency Updates'
          body: |
            ## 🔄 Dependency Updates

            This PR contains automated dependency updates:

            ### Changes:
            - ✅ Updated all dependencies to latest compatible versions
            - ✅ Fixed security vulnerabilities (moderate level)
            - ✅ All tests passing
            - ✅ Code quality checks passed

            ### Review Checklist:
            - [ ] Review dependency changes
            - [ ] Check for breaking changes
            - [ ] Verify tests still pass
            - [ ] Test application functionality

            ---
            🤖 This PR was automatically created by the dependency update workflow.
          branch: automated/dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
          assignees: ${{ github.actor }}