# Enhanced Firebase Hosting Preview on PR
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
  issues: write

env:
  NODE_VERSION: '22'

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            expense-tracker/package-lock.json
            functions/package-lock.json

      - name: Install dependencies
        working-directory: expense-tracker
        run: npm ci

      - name: Verify package.json
        working-directory: expense-tracker
        run: cat package.json | grep -A 10 '"scripts"'

      - name: Ensure public directory exists
        working-directory: expense-tracker
        run: |
          ls -la
          if [ ! -d "public" ]; then
            echo "Public directory missing, creating..."
            mkdir -p public
            echo "<!DOCTYPE html><html><head><title>Expense Tracker</title></head><body><div id='root'></div></body></html>" > public/index.html
          else
            echo "Public directory exists"
            ls -la public/
          fi

      - name: Run linting
        working-directory: expense-tracker
        run: npm run lint 2>/dev/null || echo "No lint script found"

      - name: Run tests
        working-directory: expense-tracker
        run: npm test -- --watchAll=false --passWithNoTests
        env:
          CI: true

      - name: Build application
        run: |
          cd expense-tracker
          pwd
          ls -la
          ls -la public/
          cat public/index.html | head -5
          npm run build

  build_and_preview:
    needs: test_and_build
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and deploy preview
        run: |
          cd expense-tracker
          pwd
          ls -la
          ls -la public/
          cat public/index.html | head -5
          cat package.json | grep -A 10 '"scripts"'
          npm ci
          npm run build

      - name: Ensure public directory exists (preview)
        working-directory: expense-tracker
        run: |
          if [ ! -d "public" ]; then
            echo "Public directory missing in preview, creating..."
            mkdir -p public
            echo "<!DOCTYPE html><html><head><title>Expense Tracker</title></head><body><div id='root'></div></body></html>" > public/index.html
          fi

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXPENSE_WALLET_82D9F }}
          projectId: expense-wallet-82d9f
          expires: 7d

      - name: Add preview comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔥 **Firebase Hosting Preview Ready!**\n\n' +
                    '✅ **Tests Passed**\n' +
                    '✅ **Build Successful**\n' +
                    '✅ **Preview Deployed**\n\n' +
                    '📱 **Preview URL:** ${{ steps.firebaseHostingDeploy.outputs.details_url }}\n\n' +
                    '⏰ **Expires:** 7 days from now\n\n' +
                    '---\n' +
                    '*This preview will be automatically cleaned up after the PR is merged or closed.*'
            })
